# Generated by Django 3.1.7 on 2021-03-22 10:45

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
