# Generated by Django 3.1.7 on 2021-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210319_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='id_proof',
            field=models.ImageField(default='1', upload_to='idprof'),
            preserve_default=False,
        ),
    ]
